### ISSUE TITLE
用V8作为后端启动时遇到问题

### ISSUE THREAD

**Issue by yqs112358** [Tencent/ScriptX#13]
问题描述：把小游戏demo单独提取出来，选择V8为backend，把test自动从github拉取的那个作者编译好的v8提取出来，加入项目并链接。接下来启动demo的时候报错
\#
\# Fatal error in , line 0
\# Failed to deserialize the V8 snapshot blob. This can mean that the snapshot blob file is corrupted or missing.
\#
\#
\#
\#FailureMessage Object: 0000005F167AF088
看起来像是V8快照加载失败
不知该如何解决
另外问一下v8该如何编译才能符合作为scriptx后端的要求

**Comment by LanderlYoung** [comment]
这个是你使用v8的问题，其实和ScriptX还没多大关系，你可以参考
https://github.com/Tencent/ScriptX/blob/0196ff44b908da13eefa2165885b0284758f3faa/test/src/gtest_main.cc#L87

如果你的v8使用external的snapshot数据，需要你自己初始化一下v8。

**Comment by yqs112358** [comment]
确实 加了v8::V8::InitializeExternalStartupData(".");就行了
感谢！
