### ISSUE TITLE
V8引擎作为DLL嵌入工作时出错

### ISSUE THREAD

**Issue by yqs112358** [Tencent/ScriptX#17]
如截图所示
![image](https://user-images.githubusercontent.com/37969157/114913281-9be6cb00-9e53-11eb-96ea-484820a2b3cf.png)
编译正确无警告，使用的是你预编译的V8，在单独的exe项目工作正常，，到作为DLL加载时就出问题了
不知有无遇到过这样的问题
经测试lua版dll运行正常。

由于目前没找到编译玩的x64的jscore或者quickjs所以只能搞v8。。。或者不知可否发一下您precompile完测试用的jsc或qjs(泪目)

**Comment by yqs112358** [comment]
不知dalao可否愿意qq详聊😂1425321705
一直发issue也。不太方便

**Comment by LanderlYoung** [comment]
有问题可以上github discuss https://github.com/Tencent/ScriptX/discussions 讨论，不建议开issue。
另外你这个提示是v8相关的库文件没有放到合适的位置，问题本身和ScriptX无关，建议你先学一一下v8的使用。
