### ISSUE TITLE
是否可以给Local<Number>加上区分整数 / 浮点数的能力

### ISSUE THREAD

**Issue by yqs112358** [Tencent/ScriptX#27]
尽管说Js引擎内部统一使用64位浮点数来表示数字，但是Local<Number>无法区分类型这个情况还是经常导致ScriptX数据类型在转换到C++类型时出现一定的问题，特别是做ScriptX和Json类型互转的过程当中不知该如何处理整数 / 浮点数相关的东西

**Comment by LanderlYoung** [comment]
The js language doesn't differ float/integer, so does ScriptX.

If you do need to do so, use v8_interop, js_interop, etc to use certain engine APIs.
