### ISSUE TITLE
Local<Array>'s behavior in lua may be wrong

### ISSUE THREAD

**Issue by yqs112358** [Tencent/ScriptX#31]
My test code is :
![image](https://user-images.githubusercontent.com/37969157/126248337-720b3ae8-0e6d-47ca-b712-1dc75268aa93.png)

And the result is:
![image](https://user-images.githubusercontent.com/37969157/126248356-8ef6a715-cc5c-4028-90aa-0e190895a66b.png)

It is clear that in the test code, arr is an array in lua.
It seems a bit confusing since the .isArray() returns **True** while .kind() == ValueKind::kArray returns **False**

**Comment by yqs112358** [comment]
![image](https://user-images.githubusercontent.com/37969157/126248996-d667161b-ffb7-4481-81d7-06bdd903939e.png)
![image](https://user-images.githubusercontent.com/37969157/126249011-e1190547-8ac1-44fa-8c09-57ce1ee21b54.png)

I think this may be not the best solution?

**Comment by yqs112358** [comment]
#32 I think it may be helpful

**Comment by LanderlYoung** [comment]
Yes, it is by design and well documented. Thanks for the issue and PR, will check it out later ~

**Comment by LanderlYoung** [comment]
Please check https://github.com/Tencent/ScriptX/pull/32 out, this is not a bug, it's by design and be documented cleared.
