### ISSUE TITLE
希望可以增加对 Js ESM 的支持

### ISSUE THREAD

**Issue by yqs112358** [Tencent/ScriptX#44]
lua原生require可以正常使用。但在V8 Js测试 ESM 时提示

`Uncaught SyntaxError: Cannot use import statement outside a module`

原生V8支持ESM需要通过.mjs后缀，但是由于ScriptX是基于eval的加载，没法让引擎知道当前文件需要支持ESM
貌似QuickJs就原生支持了ESM，ScriptX可以在V8这边做一些处理吗

**Comment by LanderlYoung** [comment]
这里可能和具体引擎实现有关，因此原本的打算是不做额外的支持或限制，类似JS这种推荐是使用webpack打包到一起。

**Comment by yqs112358** [comment]
okok
另外看到python backend时隔几个月之后又开始有动作啦🤪期待一波~
