### ISSUE TITLE
请问如果使用v8  on windows  是要单独编译下v8吗

### ISSUE THREAD

**Issue by yanwuguangjun** [Tencent/ScriptX#57]
请问如果使用v8  on windows  是要单独编译下v8吗
cmake 的项目 看文档中还要 libv8.a 
 关于引入到项目中的文档 可以再详细点吗 门槛感觉有点高

**Comment by LanderlYoung** [comment]
ScriptX is just an abstraction layer, you need to compile your own v8 library.

The unit test project has a v8 used for test only, see if that helps.
