### ISSUE TITLE
SCRIPTX_BACKEND gets erased by ScriptX/CMakeLists.txt

### ISSUE THREAD

**Issue by jrpat** [Tencent/ScriptX#74]
### Environment
- cmake: version 3.22.1
- ScriptX: latest master branch

### Problem

When I try to import ScriptX into my project, I follow the [ScriptX cmake guide](https://github.com/Tencent/ScriptX/blob/main/docs/en/ImportScriptX.md):

```cmake
set(SCRIPTX_BACKEND QuickJs)
include(ScriptX/CMakeLists.txt)
```

However, I get an error the first time I run cmake:

```
CMake Error at ScriptX/CMakeLists.txt:81 (message):
  Platform not set.  Please set SCRIPTX_BACKEND.  Candidates:
  V8;JavaScriptCore;SpiderMonkey;QuickJs;WebAssembly;WKWebView;Lua;Python;Ruby;Empty
```

If I run cmake again, it works now. 🧐

### Reason

This seems to be because [line 42 of CMakeLists.txt](https://github.com/Tencent/ScriptX/blob/main/CMakeLists.txt#L42) resets the variable to a blank string the first time it is run.

You can see this by adding some logging:

```cmake
message("backend: [${SCRIPTX_BACKEND}]")  # backend: [QuickJs]
set(SCRIPTX_BACKEND "" CACHE STRING "choose which ScriptX Backend(Implementation) to use, V8 or JavaScriptCore or etc...")
message("backend: [${SCRIPTX_BACKEND}]")  # backend: []
```

According to the [documentation](https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry), this is expected if [policy CMP0126](https://cmake.org/cmake/help/latest/policy/CMP0126.html#policy:CMP0126) is set to `OLD`.

That policy was introduced in version 3.21. However, since ScriptX does `cmake_minimum_required(VERSION 3.0)`, this policy is set to the `OLD` behavior (see [here](https://cmake.org/cmake/help/latest/command/cmake_policy.html#setting-policies-by-cmake-version)).

### Workaround

If you are using cmake 3.21 or newer, you can set the policy explicitly:

```cmake
# add this line first:
set(CMAKE_POLICY_DEFAULT_CMP0126 NEW)
# ...now we can do these lines:
set(SCRIPTX_BACKEND QuickJs)
include(ScriptX/CMakeLists.txt)
```

If you are running an older version, you can copy line 42 into your file and change it, like this:

```cmake
set(SCRIPTX_BACKEND QuickJs CACHE STRING "choose which ScriptX Backend(Implementation) to use, V8 or JavaScriptCore or etc...")
include(ScriptX/CMakeLists.txt)
```

### Solution

It seems there are a few options.

1. Change line 42 to make it capture the user variable:
    ````
    set(SCRIPTX_BACKEND "${SCRIPTX_BACKEND}" CACHE STRING "choose which ScriptX Backend(Implementation) to use, V8 or JavaScriptCore or etc...")
    ````
2. Change the [cmake guide](https://github.com/Tencent/ScriptX/blob/main/docs/en/ImportScriptX.md) to recommend the workarounds above.
3. Change the minimum required version to 3.21. I'm not sure if this is desirable for the project, since some users may be using older versions.

Option 1 works in my tests and seems like the cleanest fix, but I'm not sure what is best.

### Thanks

ScriptX is a really impressive library! It's well-designed and well-engineered, and promises to a be a huge benefit to my project. Thank you for making it 🎉

**Comment by LanderlYoung** [comment]
Thanks for the bug report and thorough analyses, will check this out later.

**Comment by LanderlYoung** [comment]
Looked at the test case, now it's done by

https://github.com/Tencent/ScriptX/blob/2ef15e5a50e8d56f3f50e06a90a5784c1da0e963/test/cmake/TestEnv.cmake#L38

solution 1 seems to be the cleanest one, will do this later, or a PR is welcome.
